### ISSUE TITLE
Additional sensor info from Anna/plugwise

### ISSUE THREAD

**Issue by AussiSG** [laetificat/haanna#19]
Missing the extra info which could be read out from Anna/plugwise.

Regarding:
Actual Boiler temperature.
Actual flux rating measured by thermostat.
Actual pressure in system. 

The needed to pull info is posted on following page. 
https://community.home-assistant.io/t/advice-how-to-load-sensor-info-from-plugwise-anna-thermostat-web-interface-xml/87801?page=6

**Comment by bouwew** [comment]
I've updated haanna to include getting the three requested values.

I quickly added getting the values to my private code:
![image](https://user-images.githubusercontent.com/11290930/66251118-ba431500-e74c-11e9-8ccf-4e91a260a600.png)
Looks like it's working.

How to make sensors out of these values is another matter, I could use some guidance on this topic :)

**Comment by bouwew** [comment]
Implemented and released to Pypi.

**Comment by AussiSG** [comment]
Thank you will check them later this week :D
Don't think it will be possible to really use the info to trigger your boiler/CV because Anna is already trying to do that. 

I more use it to check if pressure is below 1,8 Bar and use illumination info to switch some lighting

**Comment by bouwew** [comment]
You're welcome.
Yes, please do no test the changes today, we're still fixing some other bugs.

**Comment by bouwew** [comment]
On Pypi, haanna is updated to version 0.12.3, the requested changes have been implemented in this version.

**Comment by AussiSG** [comment]
Hi Bouwew, 
Thanks for the update. I am running the plugwise component on Home automation ( raspberry pi ). 
I have tried adding you extra line of codes in the climate.py ( looks similar to your haanna) but it doesn't seem to do the trick. 
Am I doing it wrong. 
Kind of a python newbie ;-)

**Comment by bouwew** [comment]
Just replace all the code in haanna.py and climate.py files. You can get the clean code via the Raw- button.

**Comment by AussiSG** [comment]
Should I be having both the haanna.py and the climate.py files in the custom_component folder? Thought only one should do that trick?
Sorry for asking ( so much )

**Comment by bouwew** [comment]
First you will need to update haanna, this can be done by changing the number in manifest.json. to 0.12.3. Then update the contents of climate.py with the code in the anna-ha repository.

**Comment by AussiSG** [comment]
Thank you ! Clear thing will give it a go tomorrow. 
Will let you know.

**Comment by bouwew** [comment]
Some quick advice: install the Visual Studio Code add-on from the ADD-ON STORE.
With this editor it is very easy to edit your HA files.

And here you can find the clean code to put in the climate.py file: https://raw.githubusercontent.com/laetificat/anna-ha/master/custom_components/plugwise_dev/climate.py

Just copy and paste it after deleting to existing code.
Or, if you want to play it safe, make a backup of the existing file/code. Can also be done via the Visual Studio Code editor, it has some file management functions.

**Comment by AussiSG** [comment]
Have updated the climate.py code with the code you linked above.
And also changed the number inside the .json file as followed:

```
{
  "domain": "plugwise_dev",
  "name": "Plugwise Development Anna",
  "documentation": "https://github.com/laetificat/anna-ha",
  "dependencies": [],
  "codeowners": ["@laetificat","CoMPaTech", "@bouwew"],
  "requirements": ["haanna==0.12.3"]
}

```

but when I look in the develepment tools -> states part. 
I dont see the extra information. Do I need to trigger something else.
Also did a restart of HASS after changing the code ;-)

**Comment by bouwew** [comment]
That's strange, it works for me and CoMPaTech.
Try reloading the States page.
What type of HA installation are you using? Can you check in some way if haanna was updated to the required version?

**Comment by bouwew** [comment]
Also, any information in the Development Tools - Log?

**Comment by CoMPaTech** [comment]
Not sure, but make sure you only load the dev plugwise and not (also) the actual one that is inside HA
If you do that I think that will override back to the earlier haanna

**Comment by AussiSG** [comment]
The only entry I can find in the log is:

2019-10-12 08:46:26 INFO (SyncWorker_16) [homeassistant.loader] Loaded plugwise from homeassistant.components.plugwise
2019-10-12 08:46:30 INFO (MainThread) [homeassistant.components.climate] Setting up climate.

I have added the following code in the config file to enable the logging but it feels wrong because of not getting any hehe

climate.plugwise: debug

To enable the logging but it feels wrong because of not getting any hehe

**Comment by bouwew** [comment]
I guess you have configured the Plugwise component that is a part of HA.
You can disable that one and enable the Plugwise_dev component by making a change in `configuration.yaml`:
Change
```
climate:
  - platform: plugwise
```
To
```
climate:
  - platform: plugwise_dev
```
And then restart HA.

**Comment by bouwew** [comment]
Also, you directory must be named: .../custom_components/plugwise_dev

**Comment by AussiSG** [comment]
Alright have made another step forward.... :D 
Now get the following warning 

 2019-10-12 12:15:46 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for plugwise_dev which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

But sadly enough I dont see the extra info. I have also updated the climate.py and .json file fully by downloading and putting them in /custom_components/plugwise_dev

**Comment by bouwew** [comment]
The warning is normal, so you are indeed making progress.

Can you post an image of what is shown on the States-page?
On Windows press Shift-PrintSc, open Paint, Crtl-V, then select the part of the screen you want to show here, Ctrl-C, etc.

**Comment by bouwew** [comment]
Also, you have one climate.plugwise_dev entity in the States-list? And no climate.plugwise anymore?

**Comment by AussiSG** [comment]
Yeah only got the DEV plugwise as an entity.

![image](https://user-images.githubusercontent.com/56043947/66700674-8ee39b80-ecf3-11e9-81ec-56a90dbf7192.png)

**Comment by AussiSG** [comment]
Yeah only have the DEV one as entity.

![image](https://user-images.githubusercontent.com/56043947/66700684-aae73d00-ecf3-11e9-826e-12f305ba7605.png)

**Comment by bouwew** [comment]
Ok, looks like there's more missing, what is the firmware-version of your Anna?

**Comment by AussiSG** [comment]
Its running on firmware version 1.8.20

**Comment by bouwew** [comment]
Ah, Ok, that's why. I'm running on 3.1.7 and the additions are written and tested for the 3.x firmware.
But, I'm happy to try and get it to work for your version.
Can you send me a complete capture of the Anna-xml-data?
Please browse to `"your-anna-ip"/core/domain_objects`, click with your mouse-cursor in the text that is shown, press Crtl-a, Ctrl-c and then paste (Ctrl-v) the data for instance in a pastebin.com page and send me the link.

**Comment by AussiSG** [comment]
Ah serious. I have read some stuff about that on the HA forum.... :(
Firmware version is  from 2017-03-13 and HW version = 6539-1302-5002.

hope it worked. This is the link:
https://pastebin.com/510RVMTN

**Comment by bouwew** [comment]
Great, thanks!

Please change the requirements-line in `manifest.json` from this: `"haanna==0.12.3"` to this: `"https://github.com/bouwew/haanna/archive/master.zip#haanna==0.12.4"`

Then restart HA and let me know whether the 3 new parameters are being shown.

**Comment by AussiSG** [comment]
Wauw quick progress! seems to have done the trick

![image](https://user-images.githubusercontent.com/56043947/66701382-31a01800-ecfc-11e9-846a-bc774ebadb2e.png)

**Comment by bouwew** [comment]
Great!

I see some other stuff that is not working, let me make some more changes...

**Comment by bouwew** [comment]
Ok, ready.
Please change in the requirements-line in manifest.json this: `0.12.4` to `0.12.5`. Change only the number, leave the rest as is.

Then restart HA and show me the result :)

**Comment by bouwew** [comment]
Some more fixes, please change the number to `0.12.7`, restart HA and share the result, please.

**Comment by AussiSG** [comment]
Hereby the results: 
![image](https://user-images.githubusercontent.com/56043947/66702160-e3434700-ed04-11e9-8208-772daae2c591.png)

Dont know if I see any differences ;-)

**Comment by bouwew** [comment]
I do!
Much more is working now: I can see you are running in auto-mode(= schedule is active), the available havc_modes are shown, I can see that you are tapping hot water (dhw), the available preset_modes are now correctly shown.

The only thing left to fix is the schema-stuff. I know from another legacy Anna user that you can have only one schema(=schedule). I can create several schedules and can switch between them.

My state looks like this:
![image](https://user-images.githubusercontent.com/11290930/66702258-ebe84d00-ed05-11e9-9b7a-5c06f85e43d9.png)

**Comment by AussiSG** [comment]
Ahaa nice to know. Didnt know there was a newer version avaible of the anna.  ( or the gateway )
Do you know how you can tell the difference between a newier or oldier version?

Thats why your firmware is quite higher

Indeed I can only have one time schedule for the whole week. 
I do have different modes ( Vacation mode , sleep mode , etc )

**Comment by bouwew** [comment]
Are you using the climate card?
![image](https://user-images.githubusercontent.com/11290930/66702293-4bdef380-ed06-11e9-9150-c1a11b10f619.png)

Can you please test some more?
Turn off the automation by clicking on the flame icon? Does that work?
Can you turn the automation back on by clicking the schedule icon?
Can you active a preset?
Can you manually change temperature?
Please note, wait a little while after each change for the card to update.

**Comment by bouwew** [comment]
I don't think you can see any difference in the hardwares. But the difference in firmware-version makes it clear

**Comment by bouwew** [comment]
In your attribute-list the presets are shown correctly via `preset_mode` but they show up again at `available_schemas`. And in my attribute-list there is an extra key: `selected_schema`, I will try to make that work also for your Anna.

**Comment by AussiSG** [comment]
Strangest thing is that when I try to update it states that it is up to date. So there much be some difference somewhere hehe.

Might be that plugwise has released a newer version. Of which year is your hardware version if you check it on your smile gateway site. 


Currently I am at my parents house so can't check your question but will try tomorrow

**Comment by bouwew** [comment]
That's not strange, your hardware probably can't run the new firmware.
Or maybe it can but there is a commercial reason then :)

Ok, no problem, looking forward to hear whether the control-functions work for you .

**Comment by bouwew** [comment]
One more question: the single weekschedule that is available on your Anna, does it have a fixed name or can you rename it? Or delete it and create a new one with a different name?

**Comment by bouwew** [comment]
Never mind my last question, please update the version number to `0.12.8`, restart HA and let me know the result.
I think I have fixed the detection of the schedule.

**Comment by bouwew** [comment]
Please update the version number to `0.12.9`, restart HA and show me the state.
You should no longer see `available schema's` but there should be a `selected schema` key instead.
And the schedule-name should be shown on the climate-card.

**Comment by AussiSG** [comment]
Had some time to check the climate card. 
in version 0.12.9 it looks as followed
![image](https://user-images.githubusercontent.com/56043947/66705767-56f84a80-ed2b-11e9-8e67-16ea37e47de2.png)
and I get the following message when I press the scheme button.
![image](https://user-images.githubusercontent.com/56043947/66705779-6bd4de00-ed2b-11e9-8706-636d0c309eb4.png)

**Comment by AussiSG** [comment]
The Entity looks as followed now
![image](https://user-images.githubusercontent.com/56043947/66705793-99218c00-ed2b-11e9-9a77-278169a4af7b.png)

**Comment by AussiSG** [comment]
Also the HVAC action nows says DHW. But the system is inactive at the moment. No hot water or usage of warm water for heating

**Comment by bouwew** [comment]
Hmm, that didn't work, I'll have a look.

**Comment by bouwew** [comment]
Please put version number `0.12.10` in manifest,json, restart HA and let me know the state-result.

Now I will look into the dhw issue.

**Comment by AussiSG** [comment]
Alright gonna give it a go in a minute.

PS thank you already for the much effort. And don't forget it's Saturday eve right ;-)

**Comment by bouwew** [comment]
Not sure why dhw is always on, could be a bug. I will switch it to always off for legacy Anna.
I will do that tomorrow, when you have shared the results of 0.12.10.
Enjoy your saturday-evening :)

**Comment by AussiSG** [comment]
Seems that the update gives the following error :D

```
2019-10-12 22:29:50 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.plugwise_development_thermostat fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 261, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 441, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plugwise_dev/climate.py", line 348, in update
    self._domain_objects
  File "/usr/local/lib/python3.7/site-packages/haanna/haanna.py", line 165, in get_active_schema_name
    if self.get_schema_state(self, root):
TypeError: get_schema_state() takes 2 positional arguments but 3 were given
```

**Comment by bouwew** [comment]
Goedemorgen, please try `0.12.12`.
I've fixed the error, disabled detection of dhw for legay and fixed a typo that causes showing all the presets on the climate-card.

A question: when you are tapping hot water, is a tap-icon shown on the screen of your Anna?
Please note, it will take up to a minute until the icon shows up on the screen after you start the tapping of hot water.
When the icon is there, can you please capture the xml-data once more, with the tap running hot water?

**Comment by bouwew** [comment]
One more improvement, please test `0.12.13`.

**Comment by AussiSG** [comment]
Goedemorgen, 

Correct I see a little flame icon and also a tapping icon when tapping hot water
here is the xml data when tapping hot water

https://pastebin.com/4cWC4FnA

**Comment by AussiSG** [comment]
That was during the usage of V.12 btw ;)

**Comment by bouwew** [comment]
Thanks! I'll take a look to see whether I can make dhw work for legacy Anna.

Can you show me the state? How do the attributes look now after updating to .12 / .13?

**Comment by AussiSG** [comment]
climate card looks as followed :
![image](https://user-images.githubusercontent.com/56043947/66712206-6c0bc280-ed99-11e9-9682-b1667a2ed3e0.png)

entity info:
![image](https://user-images.githubusercontent.com/56043947/66712221-a2e1d880-ed99-11e9-87b1-be7edd8ee02a.png)

**Comment by bouwew** [comment]
Ok, I checked, there is no difference in the xml w.r.t. domestic_hot_water_state.
So, the info is not in this xml.

Very good, now we are getting somewhere!
Still, I want to remove the ['...'] from the schedule name.

**Comment by bouwew** [comment]
Please test `0.12.14`.
Now the selected schema name should be without ['...'].

**Comment by bouwew** [comment]
Can you capture the xml-data from `"your-anna-ip"/core/appliances`?

**Comment by AussiSG** [comment]
Sure thing:
https://pastebin.com/6jqxk1Cm

climate card:
![image](https://user-images.githubusercontent.com/56043947/66713131-fb6ba280-eda6-11e9-82a0-81e3b1b4f0ac.png)

looks like pressing the scheme button doenst work. I thnk I could toggle it on/off when running the plugwise from inside HA

entity info:
![image](https://user-images.githubusercontent.com/56043947/66713195-bdbb4980-eda7-11e9-944d-8e7684802cde.png)

**Comment by bouwew** [comment]
Great, thanks. You were not tapping hot water when capturing the xml-data? Or were you.

**Comment by bouwew** [comment]
On pressing the scheme button when the scheme is active, that doesn't work. You have to click the flame icon or activate a preset via the 3-dots pull-down to turn the scheme off. 
This is normal behaviour as far as I know. But it could be that this is because of my programming :)

And the attributes now look as they should, nice!

**Comment by AussiSG** [comment]
Correct wasnt using any hot water or something.

Understood. When I changed back from the flame to the scheme. I get the following error:
![image](https://user-images.githubusercontent.com/56043947/66713532-53f16e80-edac-11e9-90ae-d010ae97263d.png)


![image](https://user-images.githubusercontent.com/56043947/66713542-5f449a00-edac-11e9-87ee-e0683886441f.png)

**Comment by bouwew** [comment]
Ok, then I think I cannot make detection of dhw work on the legacy Anna.

W.r.t. the error, I'll have a look.
Did that work before? Do you remember at which version it still worked?

**Comment by bouwew** [comment]
Can you shown what's in Developer Tools - Logs? Please press: Load full Home Assistant log.
Maybe there's more info on the error to be found.

**Comment by bouwew** [comment]
Never mind, please try `0.12.15`.
That should fix the reported error.

But, there will still be an error when you unselect the schedule in the Plugwise App. 
Or, can't you unselect the schedule in the App?

**Comment by AussiSG** [comment]
`Log Details (ERROR)
Sun Oct 13 2019 11:56:18 GMT+0200 (Midden-Europese zomertijd)
local variable 'template_id' referenced before assignment
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1234, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1259, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 349, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 371, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/config/custom_components/plugwise_dev/climate.py", line 328, in async_set_hvac_mode
    schema_mode,
  File "/usr/local/lib/python3.7/site-packages/haanna/haanna.py", line 126, in set_schema_state
    schema_rule_id, schema, template_id, state
UnboundLocalError: local variable 'template_id' referenced before assignment`

I think it was working on the version which is inside HA but not sure

**Comment by AussiSG** [comment]
This was on 12.14 version  btw

**Comment by bouwew** [comment]
Is it working on 12.15?

**Comment by AussiSG** [comment]
Yea I can nouw toggle between the flame and the schedule. 
Great! My wife sometimes messes with the thermostat not know where to touch the top side :D 
Now I can correct it again ;)

**Comment by bouwew** [comment]
Ok, that confirms what I thought was wrong.

Then I'm done for now :)
Next step: roll all the changes out to HA, this might take a while...

Enjoy the plugwise_dev custom_component for now.
If your want, you can update the code in climate.py, I have made a small improvement, see my github - anna-ha. Or you can wait for the release into HA.

**Comment by CoMPaTech** [comment]
You guys are on fire, nice progress!

**Comment by AussiSG** [comment]
Thank you very much for all the effort !  ( For adding only some extra sensor info ;-) ;-) haha )

**Comment by bouwew** [comment]
@AussiSG 
And thank you for providing xml-data and helping test the updates!
It finally gave us the chance in getting things to work on the legacy Anna.

Can you please close this issue?

**Comment by AussiSG** [comment]
No problem. If any more info is need just give a shout.

Sure thing!

**Comment by AussiSG** [comment]
![image](https://user-images.githubusercontent.com/56043947/66821863-779aed00-ef43-11e9-8435-c715cc2a7ab9.png)

Thanks again for the extra info :D

**Comment by bouwew** [comment]
@AussiSG please have a look at this card: https://community.home-assistant.io/t/lovelace-simple-thermostat-card/82659
The latest version works very well with my latest version on my github, also you can add additional sensors into the card. And the presets are shown as buttons on the card.

**Comment by bouwew** [comment]
@AussiSG 
Are you willing to test something for me?

I'm thinking of removing the automatic detection of the legacy Anna and turning it into a configurable parameter in configuration.yaml. That would solve the problem that another legacy user  has.
I have the code working in my non-legacy system. I would appreciate it if you could try out the code in you legacy_anna system. Looking forward hearing from you!

**Comment by AussiSG** [comment]
Hi Bouwew ,

Sure thing. What do you want me to do / test?

Do I need to load an new version of your scripts?

**Comment by bouwew** [comment]
Yes please.

Please replace the contents of your existing `climate.py` and `manifest.json` files with the contents of the files from here: https://github.com/bouwew/anna-ha-test/tree/master/custom_components/plugwise_dev

Also please add one line to `configuration.yaml`, the line with legacy_anna:
```
climate:
  - platform: plugwise_dev
    name: Your_name
    password: your_password
    host: your_host_ip
    legacy_anna: true (required for a legacy Anna, can be omitted for a recent Anna)
```
legacy_anna means an Anna device with firmware 1.8.x, as you have.

After applying all these changes please restart HA.
I expect that all the attribute information stays the same. Also, please activate a preset.
When all looks the same and you can activate the preset, then the changes I made are working properly. If not, please let me know.

**Comment by AussiSG** [comment]
`
Ontwikkelhulpmiddelen
Update for climate.plugwise_development_thermostat fails
20:48 custom_components/plugwise_dev/climate.py (ERROR) - message first occured at 6:22 and shows up 853 times
Updating device list from legacy took longer than the scheduled scan interval 0:00:10
20:47 components/device_tracker/setup.py (WARNING) - message first occured at 6:21 and shows up 2268 times
Invalid config for [climate.plugwise_dev]: [legacy_anna] is an invalid option for [climate.plugwise_dev]. Check: climate.plugwise_dev->legacy_anna. (See ?, line ?). Please check the docs at https://home-assistant.io/integrations/climate.plugwise_dev/
20:47 components/hassio/__init__.py (ERROR)
Error doing job: Exception in callback SerialTransport._read_ready()
20:13 /usr/src/homeassistant/homeassistant/core.py (ERROR) - message first occured at 7:00 and shows up 1121 times
Error handling request
19:53 /usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py (ERROR) - message first occured at 6:43 and shows up 14 times
Update of climate.plugwise_development_thermostat is taking over 10 seconds
19:34 __main__.py (WARNING) - message first occured at 17:30 and shows up 2 times
no valid packet
14:37 __main__.py (WARNING)
failed to parse packet: None
14:37 /usr/local/lib/python3.7/site-packages/rflink/protocol.py (ERROR)
You are using a custom integration for plugwise_dev which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
6:17 loader.py (WARNING)
 
Log Details (ERROR)
Mon Oct 21 2019 20:48:12 GMT+0200 (Midden-Europese zomertijd)
Update for climate.plugwise_development_thermostat fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 268, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plugwise_dev/climate.py", line 348, in update
    self._domain_objects
  File "/usr/local/lib/python3.7/site-packages/haanna/haanna.py", line 163, in get_active_schema_name
    root, locator
  File "/usr/local/lib/python3.7/site-packages/haanna/haanna.py", line 197, in get_rule_id_by_template_tag
    rule.find("template").attrib["tag"]
KeyError: 'tag'
Verbinding verbroken. Opnieuw verbinden...
`

`Log Details (ERROR)
Mon Oct 21 2019 20:47:47 GMT+0200 (Midden-Europese zomertijd)
Invalid config for [climate.plugwise_dev]: [legacy_anna] is an invalid option for [climate.plugwise_dev]. Check: climate.plugwise_dev->legacy_anna. (See ?, line ?). Please check the docs at https://home-assistant.io/integrations/climate.plugwise_dev/`

Just tried out the new version.  Giving me the following errors

**Comment by AussiSG** [comment]
It seems it aint looking to the custom version of plugwise_dev right?

**Comment by bouwew** [comment]
Can you show me your climate-entry in configuration.yaml?

**Comment by AussiSG** [comment]
Sure thing:

![image](https://user-images.githubusercontent.com/56043947/67234484-8a328c00-f445-11e9-9a44-995a48ebfff6.png)

**Comment by bouwew** [comment]
That's not what I mean. I mean the part in configuration.yaml that starts with:
```
climate:
```

**Comment by AussiSG** [comment]
Oeps sorry..... 
Should ready more carefull.....

![image](https://user-images.githubusercontent.com/56043947/67234849-2ceb0a80-f446-11e9-94cd-05539335d77f.png)

**Comment by bouwew** [comment]
That looks good.

Does your climate.py file contain this text? 
```
# Configuration directives
CONF_MIN_TEMP = "min_temp"
CONF_MAX_TEMP = "max_temp"
CONF_LEGACY = "legacy_anna"
```

**Comment by AussiSG** [comment]
Yeah looks like it:
![image](https://user-images.githubusercontent.com/56043947/67235130-c7e3e480-f446-11e9-9e92-4f525a4b797f.png)

Should give a full reboot maybe ? Only did a restart HASS?

**Comment by bouwew** [comment]
Yes please, perform a full reboot, that is the next thing to try.

**Comment by bouwew** [comment]
I think you HA restart did not happen because of the new line (legacy_anna: true) that was added.
The old code is still in memory and then the check that is performed before the restart fails, thus the error.

**Comment by CoMPaTech** [comment]
Weird, that `line 197, in get_rule_id_by_template_tag` looks like it can't find the XML part for `get_active_schema_name`. That would mean that for some reason "zone_preset_based_on_time_and_presence_with_override" can't be found in the XML (if reverse engineering it right). Please verify (before or after full reboot) if `http://10.x.x.x/core/domain_objects` has that string in it (`zone_preset_based_on_time_and_presence_with_override`)

**Comment by CoMPaTech** [comment]
also - should we reopen the closed issue? :)

**Comment by bouwew** [comment]
No, I think it is because it is executing the non-legacy code instead of the legacy-code.
In the legacy Anna XML there is no zone_preset_...

**Comment by AussiSG** [comment]
Good thinking! That must have happend. its rebooting at the moment.

Look promising:
![image](https://user-images.githubusercontent.com/56043947/67235901-59a02180-f448-11e9-8b7e-9b84cc8402d4.png)


Also tested to switch from schedule and heating mode and is still functional

**Comment by bouwew** [comment]
That looks good!
Can you please activate a preset? If that works also, then everything is working properly.

**Comment by AussiSG** [comment]
Yeah that seems to be working also ! very nice job !!! Flawless

**Comment by bouwew** [comment]
Great, thanks for checking and confirming that it works :)
That means that the HA issue #26520 is now finally solved without breaking anything for legacy Anna.

@CoMPaTech, can you please pull in both my pull-requests and release haanna 0.13.5 to Pypi?

**Comment by CoMPaTech** [comment]
@bouwew merged and uploaded

**Comment by bouwew** [comment]
@AussiSG 
I will delete my repositories now.
I suggest you make a change in your `manifest.json` file. Change 
`"requirements": ["https://github.com/bouwew/haanna_test/archive/master.zip#haanna==0.13.3"]`
to `"requirements": ["haanna==0.13.5"]`

**Comment by bouwew** [comment]
@AussiSG,
Plugwise will be updated in HA 0.102.
Unfortunately, I had to take out the illuminance sensor-value and the domestic-hot-water indication.
If you want to keep the illumination-value, better stay on the Plugwise Development version :)
I will try to find another way to add these two items later.

**Comment by AussiSG** [comment]
Hi Bouwew,
May I interrupt you with a small question. I ve just noticed now that the state HVAC of my legacy anna is not been read out? 
Currently it is heating up but shows idle on the hvac state.

Must confess that my rasberry pi crashe so I have to reinstalled everything again.
Could it be that I have some wrong files in my custom_component part? 
Or could it be that my legacy anna is unable to be read out the state?

![image](https://user-images.githubusercontent.com/56043947/72918234-9e886c80-3d45-11ea-940c-280fd10f88ae.png)

pastebin of my actual /core/appliances/
https://pastebin.com/F7tpHp3U

**Comment by AussiSG** [comment]
Think I have found something which could mean that the HVAC action is heating on a legacy anna:

<point_log id="b7d7b4f74b554f3a9d0a8c1e9505641a">
<updated_date>2020-01-22T18:40:37.793+01:00</updated_date>
<type>boiler_state</type>
<unit/>
<last_consecutive_log_date>2020-01-22T18:40:37.793+01:00</last_consecutive_log_date>
<boiler_state id="e57afa45c2194a118e2c7d81306286e0"/>
<period start_date="2020-01-22T18:40:37.793+01:00" end_date="2020-01-22T18:40:37.793+01:00">
<measurement log_date="2020-01-22T18:40:37.793+01:00">off</measurement>


Altho I can have another  Icon on my anna being displayed which is tapping hot water. This one is combined with a small flame ( indicating heating is active )

**Comment by bouwew** [comment]
Please update to the latest code first, from here: https://github.com/bouwew/anna-ha
This updated code now looks for `boiler_state` also. When found to be on, the hvac-action will be heating.

And, when you are tapping hot water, the state will be idle, as I was not allowed by the HA-reviewers to show this water-tapping-state from a climate-device.
To be able to show this state, it must come from a water_heater-device. Sometime in the future I will try to add this functionality.

So, what you see, might be correct due to the above limitation.

**Comment by bouwew** [comment]
Actually, I will add the detection of the hot water tapping but show it in HA as heating. That will solve the issue and will not violate the HA rules, I hope.

**Comment by AussiSG** [comment]
Chips missed out your messagea 3days ago. Sorry.

Will check this tomorrow or Monday and will let you know ! 
Already thanks in advance!!

**Comment by AussiSG** [comment]
Just checked your updated version. Works like a charm !

You scared me there by changing the entity name haha :D 

Thanks !

**Comment by bouwew** [comment]
@AussiSG We are working on a common platform for all Plugwise devices. There will be support for the Plugwise Anna's, Smile P1's and the Adam, and Plugs via the Adam. We have tested with the Adam, Plugs and the Anna with firmware 3.1.11. Now we are looking for testers that have a legacy Anna. Are you willing to help?

**Comment by AussiSG** [comment]
Sure thing ! Tell me what I can do for you guys to help.

**Comment by bouwew** [comment]
Ok, great!
First, disable the present component by removing the entry in your configuration.yaml, and restart HA.
Next, go here: https://github.com/plugwise/plugwise-beta and read the README. It tells you what you need to know. Any questions, let me know!

**Comment by bouwew** [comment]
Just so you know, we've released v.0.0.55 just now, with the latest fix for the legacy Anna.

**Comment by AussiSG** [comment]
Alright took some time to install it sorry about that.

Here is the stuff what I have availabe on HA: 
![image](https://user-images.githubusercontent.com/56043947/78672433-ec425900-78e0-11ea-9b99-78c1de90d2c1.png)

Preset mode show "null" ? Dont know if thats good ? ;-) 

Increasing/decreasing temperature works.

Switching modes seems to be working aswell , sleep mode , vacation mode.
altho I get an error when pressing/clicking those but dont know if that is a problem with the simple thermostart card ?

![image](https://user-images.githubusercontent.com/56043947/78673077-e7ca7000-78e1-11ea-882d-ce870f223ff8.png)

Switching to scheme mode doesnt work. I see on my simple thermostart card that it's Heating up. but the Anna in real lifes stay on the previous chosen mode ( ie sleepmode )

Also have the additional sensor there. Like illum, boiler temp , boiler pressure

**Comment by bouwew** [comment]
Ok, good! Which version are you using? The latest one on HACS: 0.1.3?
And you have a legacy Anna, correct? And what is the type of your heating system? A CV-ketel?
Also @CoMPaTech FYI

**Comment by bouwew** [comment]
@AussiSG can you please enable logging for the plugwise-beta component?
Put this in your configuration.yaml:
```

logger:
  default: info
  logs:
    custom_components.plugwise-beta: debug

```
And restart HA.
Next go to Developer Tools --> Logs and reload the detailed log below the "short" log.
There should be many debug-lines related to the plugwise-beta component, can you please post the most relevant ones here?

**Comment by bouwew** [comment]
@AussiSG Never mind, I think we found the error. Expect an updated version on HA later today.

**Comment by bouwew** [comment]
@AussiSG version 0.1.5 is ready for testing.
This should solve the preset showing null, if not, let me know.
Also, please try to set a different preset (other than the active one, when there's an active preset).

**Comment by AussiSG** [comment]
Goodmorning , 
Just updated the component with HACS. 

Preset value still shows "null" and also the schematic mode is not working.

I cant find any real error / debug stuff regarding those issue but gonna post some stuff that I found in the log:

https://pastebin.com/GFhiJE1Y

Here you see on the first line its setting the mode to auto. But in real the Anna doesnt go to the scheme / auto mode

Switch modes still work but the error show in the PIC above is still being showed in HA.
But I guess thats minor.

**Comment by CoMPaTech** [comment]
Weird, could you share your `domain_objects` (save-as not interpreted view by the browser)? It should be at http://xx.xx.xx.xx/core/domain_objects - afaik there is nothing special in there that needs privacy-filtering (also see [test anna](https://github.com/plugwise/Plugwise-Smile/blob/master/tests/legacy_anna/core.domain_objects.xml) data that we currently use)

**Comment by AussiSG** [comment]
Yeah finding it strange aswell. If I press scheme mode , a little while later it reverts back to heating mode 
This used to work normal in the anna_custom_dev version

Here is the domain_objects:
https://pastebin.com/WBm3rf8t

**Comment by bouwew** [comment]
@AussiSG you have other problems, your home-assistant database file is corrupt (sqlite3.DatabaseError). Better to delete the file home-assistant.db and restart HA.

**Comment by AussiSG** [comment]
Indeed @bouwew. 
Fixed that, thanks for pointing it out 👍 .

Sadly enough it didnt solve the problem but still doesnt give an error on setting the mode.

https://pastebin.com/SLhMSa2H

**Comment by bouwew** [comment]
@AussiSG We need to see the logged data directly from the start of HA, you are showing the data after the setting-error.

**Comment by AussiSG** [comment]
Sorry. Here is one from a fresh restart;

https://pastebin.com/3vRBeMP9

**Comment by bouwew** [comment]
@AussiSG Thank you.
I've discovered a fault in our code related to the schedule. I'm rolling out a fix. Will let you know when the new version is available on HACS.

**Comment by bouwew** [comment]
@AussiSG please try version 0.1.6.

**Comment by AussiSG** [comment]
Update but sadly enough still switches back to "heating" mode

Logs from a fresh start:
https://pastebin.com/rJZucaUH

Edit:
Preset mode now show good state 👍

**Comment by bouwew** [comment]
I see I made a typo, will fix that soon.
Nothing in the log related to set_hvac_mode.
Please wait for v0.1.7 and then try to capture the logged data related to you setting the schedule to active.

**Comment by bouwew** [comment]
@AussiSG please try version 0.1.7.

**Comment by AussiSG** [comment]
Hmmm still not. tried several times but no succes.
Also no weird stuff visible in the logs....

https://pastebin.com/pnn3bhyg

**Comment by bouwew** [comment]
Indeed, no info in the log that is usable.
Also no failed error on the screen like you showed before?

**Comment by AussiSG** [comment]
No when switching to scheme mode I dont get an error. 
Thats only when switching to a preset mode. But that switch works.

**Comment by bouwew** [comment]
Ok, clear. We'll take another good look at the code...

**Comment by bouwew** [comment]
@AussiSG please try version 0.1.8.
With this update you should be able to activate and deactivate the Thermostat schedule.

**Comment by AussiSG** [comment]
Sad to dissapoint you but still doenst stick to the schedule mode.

tried 4 times  :/ 

I got one HTTP error thingy but dont know if thats related to it.

https://pastebin.com/gAAHdbRj


Is there any other way I can help you with it ? share my screen for example or something else ?

Edit:
Hold on got some additional info. 
If I change it to schedule mode on the Anna. I also see that that mode is selected on HA.
But when I deselect it on the Anna and selected it back on in HA it doesnt put it back on schedule mode

Deselecting it on the Anna it self also shows back on HA

**Comment by bouwew** [comment]
Ok, again thanks. I think I found why this is still happening. Final fix, hopefully, on the way...

**Comment by bouwew** [comment]
@AussiSG please try with version 0.1.9.

**Comment by bouwew** [comment]
Sorry, please try v0.1.10

**Comment by AussiSG** [comment]
Currently trying version 0.1.10
When pressing the schedule button I get the following error.

![Screenshot_20200408-171803](https://user-images.githubusercontent.com/56043947/78801682-47e21480-79bd-11ea-8b46-5273a8b6ef2d.png)

**Comment by bouwew** [comment]
Sorry, a typo in the code :(

We are working on an update for the P1 v3, the fix for above error will be included in that update, to be release sometime during the evening.

**Comment by bouwew** [comment]
@AussiSG please try version 0.1.11.

**Comment by AussiSG** [comment]
Uuhh there is no new version in HACS?
Or HACS is not updated yet?

**Comment by AussiSG** [comment]
Nice great job man ! 
That looks sorted

I haven't yet try to see if the state changes form idle to hearing when the boiler is turned on.

I will check that later on when it s a bit colder again ;-)

**Comment by CoMPaTech** [comment]
He said wisely on the hottest 8th of April to date :)
Tnx for the feedback

**Comment by AussiSG** [comment]
Still have this message when setting a preset mode.
Do you have any idea if that's a fault because of using the simple thermostat card or something else ?

Setting the preset mode does work but gives this messages everytime on every preset mode ( not heating or schedule mode (

![Screenshot_20200408-200002](https://user-images.githubusercontent.com/56043947/78817604-b03bf080-79d3-11ea-93c3-ba57cdbe2b55.png)

**Comment by CoMPaTech** [comment]
Thats weird ... ill have a look

**Comment by CoMPaTech** [comment]
Can you try calling it through developer tools? 
i.e. https://yoururl/developer-tools/service like shown?

<img width="439" alt="Schermafbeelding 2020-04-08 om 20 05 41" src="https://user-images.githubusercontent.com/5751088/78818079-60a9f480-79d4-11ea-9105-388830c16adb.png">

**Comment by CoMPaTech** [comment]
I have a v3 but I'd presume it should work the same (if entered both home and away to check)

**Comment by bouwew** [comment]
@CoMPaTech see my message on Discord.

**Comment by AussiSG** [comment]
@CoMPaTech  that gives the same message

**Comment by CoMPaTech** [comment]
Yup, @bouwew already found what went wrong. Apologies from my side, redoing legacy on the rewrite I forgot key elements, kudos to @bouwew

**Comment by CoMPaTech** [comment]
We know the origin of the issue, trying to wrap my head around it but it might require review from us both so hopefully you don't mind waiting for a fix tomorrow.

**Comment by AussiSG** [comment]
Updated still gives the following messages.

Kan service climate/set_preset_mode niet aanroepen 'float' object is not subscriptable

And found another small thing which got lost in transition?
Ive lost the actual pressure of the boiler.

![image](https://user-images.githubusercontent.com/56043947/78821344-9ef5e280-79d9-11ea-9c68-a400f804331f.png)

Edit:
info can be found with the following data from core domain.


<point_log id="5934a3ae268f44af8d0f208509556b1a">
<updated_date>2020-04-08T18:55:50.400+02:00</updated_date>
<type>central_heater_water_pressure</type>
<unit>bar</unit>
<last_consecutive_log_date>2020-04-08T18:55:50.400+02:00</last_consecutive_log_date>
<pressure_gauge id="5082f6d572214c4d967b0b3212ca27b4"/>
<period start_date="2020-04-08T18:55:50.400+02:00" end_date="2020-04-08T18:55:50.400+02:00">
<measurement log_date="2020-04-08T18:55:50.400+02:00">1.80</measurement>
</period>

**Comment by AussiSG** [comment]
No problem guys , you are doing great work. 
Many thanks for this nice package already!!!

**Comment by CoMPaTech** [comment]
I'll put 0.1.12 out shortly if that doesn't work tomorrow will be a brand new shiny day

**Comment by CoMPaTech** [comment]
It should be available as for the list of issues per now

- [x] Setting prefix issue solved
- [ ] Setting prefix tested
- [ ] Boiler pressure issue investigation

**Comment by AussiSG** [comment]
@CoMPaTech , Very nice the warning/messages doenst appear any more on any of the preset modes presses

**Comment by bouwew** [comment]
@AussiSG Finally fixed! 
Thank you for your detailed testing and feedback, it helps us to find and fix all the bugs that are (were) still there after the complete make-over.

Do you also see the water_heater entity in our HA?

**Comment by bouwew** [comment]
@AussiSG About the pressure sensor, please update to version 0.1.13.
After the update it should be there, but look for it, the sensor-name has probably changed.

**Comment by AussiSG** [comment]
![image](https://user-images.githubusercontent.com/56043947/78876120-2598d700-7a4f-11ea-9234-8e8ba39bfb20.png)

Yes ! And there is also the boiler pressure sensor. 
I think I have put you guys on the wrong feet with and old sensor I created myself?....

**Comment by bouwew** [comment]
In version 0.1.12 and before the water_pressure was only available as an attribute of the water_heater.
In version 0.1.13 there is also a sensor.xyz_central_heater_water_pressure.

**Comment by AussiSG** [comment]
Yes that's awasome !
![image](https://user-images.githubusercontent.com/56043947/78877198-c2a83f80-7a50-11ea-97c6-eb6d3e49bfc8.png)

Sorry for the confusing part :D 

Edit small remark:
Dont know if you can change the "units" in the base entity. 
I think its Bar and not milibars ( mbar )

**Comment by bouwew** [comment]
Yes, you are right. In my Adam-system and I think in the recent Anna the number is an integer (0-10), that's why I changed it. I will investigate...

**Comment by AussiSG** [comment]
Its not a real problem , you can ofcourse change the units by hand.
So I wouldnt bother changing it for legacy Anna's 
As it seems there are more V3 users haha

**Comment by bouwew** [comment]
Will be fixed in 0.1.14, sometime later today...

**Comment by AussiSG** [comment]
Hi Gents I am currently running 0.2.0 on HA on version 219.
Got everything running. But I dont get the climate entity?

I do get 2 entities called "Anna" and "Smile_Anna" but they only contain information. ( i.e. sensors )

![image](https://user-images.githubusercontent.com/56043947/80515154-c8bf7b00-8981-11ea-97b0-46779f10c971.png)

**Comment by bouwew** [comment]
Sorry, which HA version are you on?

**Comment by CoMPaTech** [comment]
Presumablye 109b4 (which is 219 here as well)... do you spot anything obvious in `/developer-tools/logs`? I guess the climate part just isn't loading, we're very keen to understand why

**Comment by bouwew** [comment]
219 is the supervisor version, can still be 0.108.x.

**Comment by CoMPaTech** [comment]
Lets follow up in the above mentioned issue
